import { useState, useRef } from "react";

export default function GameMapScreen(){

  const mapRef = useRef(null)

    const [zoom,setZoom] = useState(1)

      const MIN_ZOOM = 0.6
        const MAX_ZOOM = 2

          function zoomIn(){
              setZoom((z)=>Math.min(z+0.15,MAX_ZOOM))
                }

                  function zoomOut(){
                      setZoom((z)=>Math.max(z-0.15,MIN_ZOOM))
                        }

                          function handleWheel(e){

                              e.preventDefault()

                                  let newZoom = zoom - e.deltaY * 0.001

                                      if(newZoom < MIN_ZOOM) newZoom = MIN_ZOOM
                                          if(newZoom > MAX_ZOOM) newZoom = MAX_ZOOM

                                              setZoom(newZoom)

                                                }

                                                  return(

                                                      <div className="w-screen h-screen bg-black overflow-hidden flex items-center justify-center">

                                                            <div
                                                                    style={{
                                                                              position:"relative",
                                                                                        width:"100%",
                                                                                                  height:"100%",
                                                                                                            overflow:"hidden"
                                                                                                                    }}
                                                                                                                          >

                                                                                                                                  {/* MAPA */}

                                                                                                                                          <div
                                                                                                                                                    ref={mapRef}
                                                                                                                                                              onWheel={handleWheel}
                                                                                                                                                                        style={{
                                                                                                                                                                                    width:"100%",
                                                                                                                                                                                                height:"100%",
                                                                                                                                                                                                            transform:`scale(${zoom})`,
                                                                                                                                                                                                                        transformOrigin:"center center",
                                                                                                                                                                                                                                    transition:"transform 0.05s linear"
                                                                                                                                                                                                                                              }}
                                                                                                                                                                                                                                                      >

                                                                                                                                                                                                                                                                <img
                                                                                                                                                                                                                                                                            src="/mapa-cidade.png"
                                                                                                                                                                                                                                                                                        style={{
                                                                                                                                                                                                                                                                                                      width:"100%",
                                                                                                                                                                                                                                                                                                                    height:"100%",
                                                                                                                                                                                                                                                                                                                                  objectFit:"cover",
                                                                                                                                                                                                                                                                                                                                                pointerEvents:"none"
                                                                                                                                                                                                                                                                                                                                                            }}
                                                                                                                                                                                                                                                                                                                                                                      />

                                                                                                                                                                                                                                                                                                                                                                              </div>

                                                                                                                                                                                                                                                                                                                                                                                      {/* CONTROLE ZOOM */}

                                                                                                                                                                                                                                                                                                                                                                                              <div
                                                                                                                                                                                                                                                                                                                                                                                                        style={{
                                                                                                                                                                                                                                                                                                                                                                                                                    position:"absolute",
                                                                                                                                                                                                                                                                                                                                                                                                                                right:20,
                                                                                                                                                                                                                                                                                                                                                                                                                                            bottom:20,
                                                                                                                                                                                                                                                                                                                                                                                                                                                        display:"flex",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    flexDirection:"column",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                gap:10
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  >

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        onClick={zoomIn}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    style={{
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  width:45,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                height:45,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              background:"#111",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            color:"white",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          border:"1px solid #444",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        borderRadius:8,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      fontSize:22
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        +
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </button>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        onClick={zoomOut}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    style={{
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  width:45,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                height:45,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              background:"#111",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            color:"white",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          border:"1px solid #444",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        borderRadius:8,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      fontSize:22
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        −
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </button>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      )

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }
