TypeScript

type SkillKey =
  | 'inteligencia'
    | 'agilidade'
      | 'ataque'
        | 'defesa'
          | 'respeito'
            | 'vigor';

            type LuxuryItemType = {
              id: number;
                baseName: string;
                  image: string;
                    skill: SkillKey;
                    };

                    type PurchaseState = Record<number, boolean>;

                    type DialogTone = 'welcome' | 'click' | 'purchase' | 'insufficient' | 'owned';

                    type DialogState = {
                      open: boolean;
                        title: string;
                          message: string;
                            tone: DialogTone;
                            };

                            type PurchaseAnimationState = {
                              open: boolean;
                                itemName: string;
                                  price: number;
                                  };

                                  const collectionNames: Record<number, string> = {
                                    1: 'Básico',
                                      2: 'Simples',
                                        3: 'Refinado',
                                          4: 'Premium',
                                            5: 'Luxo',
                                              6: 'Elite',
                                                7: 'Supremo',
                                                  8: 'Imperial',
                                                    9: 'Real',
                                                      10: 'Magnata',
                                                        11: 'Aristocrata',
                                                          12: 'Nobre',
                                                            13: 'Dinastia',
                                                              14: 'Herança',
                                                                15: 'Fortuna',
                                                                  16: 'Prestige',
                                                                    17: 'Elite Suprema',
                                                                      18: 'Império',
                                                                        19: 'Apex',
                                                                          20: 'Soberano',
                                                                            21: 'Monarca',
                                                                              22: 'Coroa',
                                                                                23: 'Platinum',
                                                                                  24: 'Royal',
                                                                                    25: 'Infinite',
                                                                                      26: 'Legacy',
                                                                                        27: 'Obsidian',
                                                                                          28: 'Velvet',
                                                                                            29: 'Noir',
                                                                                              30: 'Zenith',
                                                                                                31: 'Imperial Noir',
                                                                                                  32: 'Crown Legacy',
                                                                                                    33: 'Supreme Dynasty',
                                                                                                      34: 'Golden Empire',
                                                                                                        35: 'Infinite Prestige',
                                                                                                          36: 'Platinum Empire',
                                                                                                            37: 'Diamond Sovereign',
                                                                                                              38: 'Black Crown',
                                                                                                                39: 'Obsidian Royalty',
                                                                                                                  40: 'Apex Dynasty',
                                                                                                                    41: 'Syndicate',
                                                                                                                      42: 'Mafia Royale',
                                                                                                                        43: 'Casino Prestige',
                                                                                                                          44: 'Diamond Syndicate',
                                                                                                                            45: 'Black Market',
                                                                                                                              46: 'Underworld',
                                                                                                                                47: 'Crimson Empire',
                                                                                                                                  48: 'Platinum Syndicate',
                                                                                                                                    49: 'Cartel Elite',
                                                                                                                                      50: 'Apex Underworld',
                                                                                                                                        51: 'Billionaire',
                                                                                                                                          52: 'Global Elite',
                                                                                                                                            53: 'Supreme Capital',
                                                                                                                                              54: 'Infinite Wealth',
                                                                                                                                                55: 'Ultra Dynasty',
                                                                                                                                                  56: 'Titan',
                                                                                                                                                    57: 'Apex Billionaire',
                                                                                                                                                      58: 'Supreme Mogul',
                                                                                                                                                        59: 'Infinite Empire',
                                                                                                                                                          60: 'Ultimate Sovereign',
                                                                                                                                                            61: 'Eternal',
                                                                                                                                                              62: 'Divine',
                                                                                                                                                                63: 'Celestial',
                                                                                                                                                                  64: 'Infinite Aura',
                                                                                                                                                                    65: 'Obsidian Legend',
                                                                                                                                                                      66: 'Diamond Eternity',
                                                                                                                                                                        67: 'Mythic',
                                                                                                                                                                          68: 'Majesty',
                                                                                                                                                                            69: 'Cosmic',
                                                                                                                                                                              70: 'Apex Infinity',
                                                                                                                                                                                71: 'Eternal Apex',
                                                                                                                                                                                  72: 'Divine Infinity',
                                                                                                                                                                                    73: 'Celestial Apex',
                                                                                                                                                                                      74: 'Infinite Divinity',
                                                                                                                                                                                        75: 'Godtier',
                                                                                                                                                                                          76: 'Immortal',
                                                                                                                                                                                            77: 'Mythic Infinity',
                                                                                                                                                                                              78: 'Supreme Eternity',
                                                                                                                                                                                                79: 'Cosmic Apex',
                                                                                                                                                                                                  80: 'Absolute Infinity',
                                                                                                                                                                                                    81: 'Eternal God',
                                                                                                                                                                                                      82: 'Divinity Prime',
                                                                                                                                                                                                        83: 'Celestial Absolute',
                                                                                                                                                                                                          84: 'Apex Divinity',
                                                                                                                                                                                                            85: 'Godhood',
                                                                                                                                                                                                              86: 'Absolute Supreme',
                                                                                                                                                                                                                87: 'Omnipotent',
                                                                                                                                                                                                                  88: 'Transcendent',
                                                                                                                                                                                                                    89: 'Cosmic Supreme',
                                                                                                                                                                                                                      90: 'Overlord',
                                                                                                                                                                                                                        91: 'Creator',
                                                                                                                                                                                                                          92: 'Absolute Creator',
                                                                                                                                                                                                                            93: 'Architect',
                                                                                                                                                                                                                              94: 'Infinite Architect',
                                                                                                                                                                                                                                95: 'Supreme Entity',
                                                                                                                                                                                                                                  96: 'Absolute Entity',
                                                                                                                                                                                                                                    97: 'Eternal Entity',
                                                                                                                                                                                                                                      98: 'Infinite Entity',
                                                                                                                                                                                                                                        99: 'Supreme Infinity',
                                                                                                                                                                                                                                          100: 'Domínio do Comando',
                                                                                                                                                                                                                                          };
                                                                                                                                                                                                                                          const luxuryItemTypes: LuxuryItemType[] = [
                                                                                                                                                                                                                                              {
                                                                                                                                                                                                                                                  id: 0,
                                                                                                                                                                                                                                                      baseName: 'Anel',
                                                                                                                                                                                                                                                          image:
                                                                                                                                                                                                                                                                'https://static.wixstatic.com/media/50f4bf_b4ba3afc05854898ba783d0de389365c~mv2.png',
                                                                                                                                                                                                                                                                    skill: 'respeito',
                                                                                                                                                                                                                                                                      },
                                                                                                                                                                                                                                                                        {
                                                                                                                                                                                                                                                                            id: 1,
                                                                                                                                                                                                                                                                                baseName: 'Pulseira',
                                                                                                                                                                                                                                                                                    image:
                                                                                                                                                                                                                                                                                          'https://static.wixstatic.com/media/50f4bf_80f3ea6ada6a4239b5fde6e862c0f4b0~mv2.png',
                                                                                                                                                                                                                                                                                              skill: 'agilidade',
                                                                                                                                                                                                                                                                                                },
                                                                                                                                                                                                                                                                                                  {
                                                                                                                                                                                                                                                                                                      id: 2,
                                                                                                                                                                                                                                                                                                          baseName: 'Corrente',
                                                                                                                                                                                                                                                                                                              image:
                                                                                                                                                                                                                                                                                                                    'https://static.wixstatic.com/media/50f4bf_24463c72375a4151be5f718bd0169cab~mv2.png',
                                                                                                                                                                                                                                                                                                                        skill: 'ataque',
                                                                                                                                                                                                                                                                                                                          },
                                                                                                                                                                                                                                                                                                                            {
                                                                                                                                                                                                                                                                                                                                id: 3,
                                                                                                                                                                                                                                                                                                                                    baseName: 'Relógio',
                                                                                                                                                                                                                                                                                                                                        image:
                                                                                                                                                                                                                                                                                                                                              'https://static.wixstatic.com/media/50f4bf_3f8630e8f4a845d581213e7fc906ba09~mv2.png',
                                                                                                                                                                                                                                                                                                                                                  skill: 'inteligencia',
                                                                                                                                                                                                                                                                                                                                                    },
                                                                                                                                                                                                                                                                                                                                                      {
                                                                                                                                                                                                                                                                                                                                                          id: 4,
                                                                                                                                                                                                                                                                                                                                                              baseName: 'Bolsa',
                                                                                                                                                                                                                                                                                                                                                                  image:
                                                                                                                                                                                                                                                                                                                                                                        'https://static.wixstatic.com/media/50f4bf_0f2cb270b40649d4a24e14b5aa4788bc~mv2.png',
                                                                                                                                                                                                                                                                                                                                                                            skill: 'defesa',
                                                                                                                                                                                                                                                                                                                                                                              },
                                                                                                                                                                                                                                                                                                                                                                                {
                                                                                                                                                                                                                                                                                                                                                                                    id: 5,
                                                                                                                                                                                                                                                                                                                                                                                        baseName: 'Óculos',
                                                                                                                                                                                                                                                                                                                                                                                            image:
                                                                                                                                                                                                                                                                                                                                                                                                  'https://static.wixstatic.com/media/50f4bf_01707feefbb346e09308f3739d8586a8~mv2.png',
                                                                                                                                                                                                                                                                                                                                                                                                      skill: 'vigor',
                                                                                                                                                                                                                                                                                                                                                                                                        },
                                                                                                                                                                                                                                                                                                                                                                                                        ];

                                                                                                                                                                                                                                                                                                                                                                                                        function clampLevel(level: number) {
                                                                                                                                                                                                                                                                                                                                                                                                          return Math.min(100, Math.max(1, level || 1));
                                                                                                                                                                                                                                                                                                                                                                                                          }

                                                                                                                                                                                                                                                                                                                                                                                                          function getCollectionName(level: number) {
                                                                                                                                                                                                                                                                                                                                                                                                            return collectionNames[clampLevel(level)] || `Nível ${level}`;
                                                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                                            function getBackgroundByLevel(level: number) {
                                                                                                                                                                                                                                                                                                                                                                                                              if (level <= 10) return 'linear-gradient(135deg, #181818 0%, #0b0b0b 100%)';
                                                                                                                                                                                                                                                                                                                                                                                                                if (level <= 25) return 'linear-gradient(135deg, #101628 0%, #1f3564 100%)';
                                                                                                                                                                                                                                                                                                                                                                                                                  if (level <= 50) return 'linear-gradient(135deg, #16061d 0%, #4d0f75 100%)';
                                                                                                                                                                                                                                                                                                                                                                                                                    if (level <= 75) return 'linear-gradient(135deg, #080808 0%, #2b2105 45%, #c4971b 100%)';
                                                                                                                                                                                                                                                                                                                                                                                                                      if (level <= 90) return 'radial-gradient(circle at 20% 20%, #ffe58a 0%, #5a470c 25%, #050505 100%)';
                                                                                                                                                                                                                                                                                                                                                                                                                        return 'radial-gradient(circle at 50% 40%, #ffffff 0%, #ffd700 20%, #0a0a0a 75%)';
                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                        function getThemeByLevel(level: number) {
                                                                                                                                                                                                                                                                                                                                                                                                                          if (level <= 10) {
                                                                                                                                                                                                                                                                                                                                                                                                                              return {
                                                                                                                                                                                                                                                                                                                                                                                                                                    accent: '#7d7d7d',
                                                                                                                                                                                                                                                                                                                                                                                                                                          accentSoft: 'rgba(125,125,125,0.25)',
                                                                                                                                                                                                                                                                                                                                                                                                                                                card: 'linear-gradient(135deg, rgba(45,45,45,0.92), rgba(10,10,10,0.92))',
                                                                                                                                                                                                                                                                                                                                                                                                                                                      textGlow: '0 0 18px rgba(255,255,255,0.18)',
                                                                                                                                                                                                                                                                                                                                                                                                                                                          };
                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                              if (level <= 25) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  return {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        accent: '#4ba3ff',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              accentSoft: 'rgba(75,163,255,0.25)',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    card: 'linear-gradient(135deg, rgba(13,29,59,0.95), rgba(7,9,17,0.95))',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          textGlow: '0 0 18px rgba(75,163,255,0.35)',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  if (level <= 50) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      return {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            accent: '#b663ff',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  accentSoft: 'rgba(182,99,255,0.25)',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        card: 'linear-gradient(135deg, rgba(42,10,59,0.95), rgba(8,4,15,0.95))',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              textGlow: '0 0 18px rgba(182,99,255,0.35)',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      if (level <= 75) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          return {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                accent: '#d9aa26',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      accentSoft: 'rgba(217,170,38,0.26)',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            card: 'linear-gradient(135deg, rgba(18,18,18,0.95), rgba(54,39,4,0.95))',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  textGlow: '0 0 18px rgba(217,170,38,0.4)',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          if (level <= 90) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              return {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    accent: '#ffd700',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          accentSoft: 'rgba(255,215,0,0.26)',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                card: 'linear-gradient(135deg, rgba(20,20,20,0.95), rgba(82,62,7,0.95))',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      textGlow: '0 0 18px rgba(255,215,0,0.45)',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              return {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  accent: '#ffffff',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      accentSoft: 'rgba(255,255,255,0.3)',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          card: 'linear-gradient(135deg, rgba(22,22,22,0.95), rgba(92,74,12,0.95))',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              textGlow: '0 0 24px rgba(255,255,255,0.55)',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                function getItemPrice(level: number) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  const basePrice = 120;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    return Number((basePrice * Math.pow(1.1, level - 1)).toFixed(2));
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    function getItemAccent(level: number, itemIndex: number) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      const palette = [
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          ['#f7d774', '#b98b0d'],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ['#6ce8ff', '#1583b8'],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ['#ff7ccf', '#a31d71'],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      ['#c6a0ff', '#6937c6'],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          ['#76ffa4', '#0f9a4a'],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ['#ffe4a3', '#cf7f1e'],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ];
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  const pair = palette[itemIndex % palette.length];
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    const rotate = Math.min(140, level * 1.5);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      return {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          primary: pair[0],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              secondary: pair[1],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  overlay: `hsla(${(rotate + itemIndex * 35) % 360}, 80%, 55%, 0.16)`,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      filter: `hue-rotate(${(level * 7 + itemIndex * 23) % 360}deg) saturate(${1 + level / 130})`,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                          ]
