import { useEffect, useRef } from 'react';
import * as THREE from 'three';

export default function CinematicSignboard() {
  const containerRef = useRef<HTMLDivElement>(null);

    useEffect(() => {
        if (!containerRef.current) return;

            // Configuração da Cena - Tons de azul profundo e preto absoluto
                const scene = new THREE.Scene();
                    scene.background = new THREE.Color(0x020205);
                        scene.fog = new THREE.Fog(0x020205, 10, 150);

                            const camera = new THREE.PerspectiveCamera(60, window.innerWidth / window.innerHeight, 0.1, 1000);
                                // Começa longe para o zoom de impacto
                                    camera.position.set(0, 5, 80);

                                        const renderer = new THREE.WebGLRenderer({ antialias: true, powerPreference: "high-performance" });
                                            renderer.setSize(window.innerWidth, window.innerHeight);
                                                renderer.setPixelRatio(Math.min(window.devicePixelRatio, 2));
                                                    renderer.toneMapping = THREE.ReinhardToneMapping;
                                                        containerRef.current.appendChild(renderer.domElement);

                                                            // Iluminação de Ostentação
                                                                const ambientLight = new THREE.AmbientLight(0xffffff, 0.1);
                                                                    scene.add(ambientLight);

                                                                        // Luz principal "Dourada"
                                                                            const goldSpot = new THREE.PointLight(0xffd700, 5, 100);
                                                                                goldSpot.position.set(0, 10, 20);
                                                                                    scene.add(goldSpot);

                                                                                        // Luz de contorno Neon "Comando" (Cyan/Azul)
                                                                                            const neonLight = new THREE.RectAreaLight(0x00f2ff, 10, 50, 10);
                                                                                                neonLight.position.set(0, 0, -2);
                                                                                                    scene.add(neonLight);

                                                                                                        // Criação do Texto (Usando Canvas de Alta Resolução)
                                                                                                            const canvas = document.createElement('canvas');
                                                                                                                canvas.width = 2048;
                                                                                                                    canvas.height = 512;
                                                                                                                        const ctx = canvas.getContext('2d');
                                                                                                                            if (ctx) {
                                                                                                                                  // Background transparente para o metal brilhar
                                                                                                                                        ctx.clearRect(0, 0, canvas.width, canvas.height);
                                                                                                                                              ctx.font = 'black 160px "Impact", sans-serif';
                                                                                                                                                    ctx.textAlign = 'center';
                                                                                                                                                          ctx.textBaseline = 'middle';

                                                                                                                                                                      // Camada de Brilho Externo (Glow)
                                                                                                                                                                            ctx.shadowColor = '#00f2ff';
                                                                                                                                                                                  ctx.shadowBlur = 40;
                                                                                                                                                                                        ctx.strokeStyle = '#00f2ff';
                                                                                                                                                                                              ctx.lineWidth = 10;
                                                                                                                                                                                                    ctx.strokeText('COMPLEXO 1 DO COMANDO NORTE', canvas.width / 2, canvas.height / 2);

                                                                                                                                                                                                          // Texto Principal Dourado Metálico
                                                                                                                                                                                                                const gradient = ctx.createLinearGradient(0, 150, 0, 350);
                                                                                                                                                                                                                      gradient.addColorStop(0, '#fff3a0');
                                                                                                                                                                                                                            gradient.addColorStop(0.5, '#ffd700');
                                                                                                                                                                                                                                  gradient.addColorStop(1, '#b8860b');

                                                                                                                                                                                                                                              ctx.shadowBlur = 0;
                                                                                                                                                                                                                                                    ctx.fillStyle = gradient;
                                                                                                                                                                                                                                                          ctx.fillText('COMPLEXO 1 DO COMANDO NORTE', canvas.width / 2, canvas.height / 2);
                                                                                                                                                                                                                                                              }

                                                                                                                                                                                                                                                                  const texture = new THREE.CanvasTexture(canvas);
                                                                                                                                                                                                                                                                      const material = new THREE.MeshStandardMaterial({
                                                                                                                                                                                                                                                                            map: texture,
                                                                                                                                                                                                                                                                                  transparent: true,
                                                                                                                                                                                                                                                                                        metalness: 1,
                                                                                                                                                                                                                                                                                              roughness: 0.1,
                                                                                                                                                                                                                                                                                                    emissive: new THREE.Color(0xffd700),
                                                                                                                                                                                                                                                                                                          emissiveIntensity: 0.5
                                                                                                                                                                                                                                                                                                              });

                                                                                                                                                                                                                                                                                                                  const geometry = new THREE.PlaneGeometry(60, 15);
                                                                                                                                                                                                                                                                                                                      const mesh = new THREE.Mesh(geometry, material);
                                                                                                                                                                                                                                                                                                                          scene.add(mesh);

                                                                                                                                                                                                                                                                                                                              // Partículas de "Conflito" (Faíscas/Poeira no ar)
                                                                                                                                                                                                                                                                                                                                  const pCount = 500;
                                                                                                                                                                                                                                                                                                                                      const pGeometry = new THREE.BufferGeometry();
                                                                                                                                                                                                                                                                                                                                          const pPos = new Float32Array(pCount * 3);
                                                                                                                                                                                                                                                                                                                                              for(let i=0; i<pCount*3; i++) pPos[i] = (Math.random() - 0.5) * 150;
                                                                                                                                                                                                                                                                                                                                                  pGeometry.setAttribute('position', new THREE.BufferAttribute(pPos, 3));
                                                                                                                                                                                                                                                                                                                                                      const pMaterial = new THREE.PointsMaterial({ color: 0xffaa00, size: 0.2, transparent: true, opacity: 0.8 });
                                                                                                                                                                                                                                                                                                                                                          const sparks = new THREE.Points(pGeometry, pMaterial);
                                                                                                                                                                                                                                                                                                                                                              scene.add(sparks);

                                                                                                                                                                                                                                                                                                                                                                  // Animação de Impacto
                                                                                                                                                                                                                                                                                                                                                                      let frame = 0;
                                                                                                                                                                                                                                                                                                                                                                          const animate = () => {
                                                                                                                                                                                                                                                                                                                                                                                frame++;
                                                                                                                                                                                                                                                                                                                                                                                      requestAnimationFrame(animate);

                                                                                                                                                                                                                                                                                                                                                                                            // Zoom "Tarantino" (Rápido no início, suave no fim)
                                                                                                                                                                                                                                                                                                                                                                                                  if (camera.position.z > 25) {
                                                                                                                                                                                                                                                                                                                                                                                                          camera.position.z -= 0.8;
                                                                                                                                                                                                                                                                                                                                                                                                                } else {
                                                                                                                                                                                                                                                                                                                                                                                                                        // Leve tremor de câmera constante após o zoom
                                                                                                                                                                                                                                                                                                                                                                                                                                camera.position.x = Math.sin(frame * 0.1) * 0.05;
                                                                                                                                                                                                                                                                                                                                                                                                                                        camera.position.y = 5 + Math.cos(frame * 0.1) * 0.05;
                                                                                                                                                                                                                                                                                                                                                                                                                                              }

                                                                                                                                                                                                                                                                                                                                                                                                                                                    // Rotação sutil de poder
                                                                                                                                                                                                                                                                                                                                                                                                                                                          mesh.rotation.y = Math.sin(frame * 0.01) * 0.05;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                // Efeito de Flicker (Luz falhando estilo favela)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      const flicker = Math.random() > 0.95 ? 0.2 : 1;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            material.emissiveIntensity = (0.4 + Math.sin(frame * 0.05) * 0.2) * flicker;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  // Movimento das faíscas
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        sparks.rotation.y += 0.001;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              sparks.position.y -= 0.05;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if(sparks.position.y < -20) sparks.position.y = 20;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          renderer.render(scene, camera);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              };

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  animate();

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      const handleResize = () => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            camera.aspect = window.innerWidth / window.innerHeight;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  camera.updateProjectionMatrix();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        renderer.setSize(window.innerWidth, window.innerHeight);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                window.addEventListener('resize', handleResize);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    return () => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          window.removeEventListener('resize', handleResize);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                containerRef.current?.removeChild(renderer.domElement);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }, []);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        return <div ref={containerRef} className="w-full h-screen bg-black" />;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
