import { useEffect, useRef } from "react";
import * as THREE from "three";

export default function GameIntro() {
  const containerRef = useRef<HTMLDivElement>(null);

    useEffect(() => {
        if (!containerRef.current) return;

            const scene = new THREE.Scene();
                scene.background = new THREE.Color(0x000000);
                    scene.fog = new THREE.Fog(0x000000, 30, 300);

                        const camera = new THREE.PerspectiveCamera(
                              70,
                                    window.innerWidth / window.innerHeight,
                                          0.1,
                                                1000
                                                    );

                                                        camera.position.set(0, 15, 220);

                                                            const renderer = new THREE.WebGLRenderer({
                                                                  antialias: true,
                                                                        powerPreference: "high-performance",
                                                                            });

                                                                                renderer.setPixelRatio(window.devicePixelRatio);
                                                                                    renderer.setSize(window.innerWidth, window.innerHeight);
                                                                                        containerRef.current.appendChild(renderer.domElement);

                                                                                            // Luz ambiente
                                                                                                const ambient = new THREE.AmbientLight(0xffffff, 0.3);
                                                                                                    scene.add(ambient);

                                                                                                        // Holofote principal
                                                                                                            const spot = new THREE.SpotLight(0xffd700, 6, 300, Math.PI / 4, 0.5, 1);
                                                                                                                spot.position.set(0, 80, 40);
                                                                                                                    scene.add(spot);

                                                                                                                        // Neon inferior
                                                                                                                            const neon = new THREE.PointLight(0x00eaff, 2, 120);
                                                                                                                                neon.position.set(0, -8, 20);
                                                                                                                                    scene.add(neon);

                                                                                                                                        // ==========================
                                                                                                                                            // LETREIRO
                                                                                                                                                // ==========================

                                                                                                                                                    const group = new THREE.Group();
                                                                                                                                                        scene.add(group);

                                                                                                                                                            const canvas = document.createElement("canvas");
                                                                                                                                                                canvas.width = 2048;
                                                                                                                                                                    canvas.height = 512;

                                                                                                                                                                        const ctx = canvas.getContext("2d");

                                                                                                                                                                            if (ctx) {
                                                                                                                                                                                  ctx.fillStyle = "#050505";
                                                                                                                                                                                        ctx.fillRect(0, 0, canvas.width, canvas.height);

                                                                                                                                                                                              ctx.font = '900 170px "Impact", "Arial Black", sans-serif';
                                                                                                                                                                                                    ctx.textAlign = "center";
                                                                                                                                                                                                          ctx.textBaseline = "middle";

                                                                                                                                                                                                                const grad = ctx.createLinearGradient(0, 120, 0, 380);

                                                                                                                                                                                                                      grad.addColorStop(0, "#fff6b0");
                                                                                                                                                                                                                            grad.addColorStop(0.5, "#ffd700");
                                                                                                                                                                                                                                  grad.addColorStop(1, "#8b6b2c");

                                                                                                                                                                                                                                        ctx.shadowColor = "#00eaff";
                                                                                                                                                                                                                                              ctx.shadowBlur = 40;

                                                                                                                                                                                                                                                    ctx.fillStyle = grad;

                                                                                                                                                                                                                                                          ctx.fillText(
                                                                                                                                                                                                                                                                  "COMPLEXO DO COMANDO NORTE",
                                                                                                                                                                                                                                                                          canvas.width / 2,
                                                                                                                                                                                                                                                                                  canvas.height / 2
                                                                                                                                                                                                                                                                                        );
                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                const texture = new THREE.CanvasTexture(canvas);

                                                                                                                                                                                                                                                                                                    const material = new THREE.MeshStandardMaterial({
                                                                                                                                                                                                                                                                                                          map: texture,
                                                                                                                                                                                                                                                                                                                metalness: 1,
                                                                                                                                                                                                                                                                                                                      roughness: 0.2,
                                                                                                                                                                                                                                                                                                                            emissive: new THREE.Color(0xffd700),
                                                                                                                                                                                                                                                                                                                                  emissiveIntensity: 0.7,
                                                                                                                                                                                                                                                                                                                                      });

                                                                                                                                                                                                                                                                                                                                          const sign = new THREE.Mesh(new THREE.PlaneGeometry(60, 15), material);
                                                                                                                                                                                                                                                                                                                                              group.add(sign);

                                                                                                                                                                                                                                                                                                                                                  const frame = new THREE.Mesh(
                                                                                                                                                                                                                                                                                                                                                        new THREE.BoxGeometry(64, 19, 1),
                                                                                                                                                                                                                                                                                                                                                              new THREE.MeshStandardMaterial({
                                                                                                                                                                                                                                                                                                                                                                      color: 0xffd700,
                                                                                                                                                                                                                                                                                                                                                                              metalness: 1,
                                                                                                                                                                                                                                                                                                                                                                                      roughness: 0.2,
                                                                                                                                                                                                                                                                                                                                                                                            })
                                                                                                                                                                                                                                                                                                                                                                                                );

                                                                                                                                                                                                                                                                                                                                                                                                    frame.position.z = -0.4;

                                                                                                                                                                                                                                                                                                                                                                                                        group.add(frame);

                                                                                                                                                                                                                                                                                                                                                                                                            // ==========================
                                                                                                                                                                                                                                                                                                                                                                                                                // PARTÍCULAS (POEIRA URBANA)
                                                                                                                                                                                                                                                                                                                                                                                                                    // ==========================

                                                                                                                                                                                                                                                                                                                                                                                                                        const particles = new THREE.BufferGeometry();
                                                                                                                                                                                                                                                                                                                                                                                                                            const particleCount = 1200;

                                                                                                                                                                                                                                                                                                                                                                                                                                const positions = new Float32Array(particleCount * 3);

                                                                                                                                                                                                                                                                                                                                                                                                                                    for (let i = 0; i < particleCount; i++) {
                                                                                                                                                                                                                                                                                                                                                                                                                                          positions[i * 3] = (Math.random() - 0.5) * 200;
                                                                                                                                                                                                                                                                                                                                                                                                                                                positions[i * 3 + 1] = Math.random() * 80 - 20;
                                                                                                                                                                                                                                                                                                                                                                                                                                                      positions[i * 3 + 2] = (Math.random() - 0.5) * 200;
                                                                                                                                                                                                                                                                                                                                                                                                                                                          }

                                                                                                                                                                                                                                                                                                                                                                                                                                                              particles.setAttribute(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    "position",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          new THREE.BufferAttribute(positions, 3)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              );

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  const particleMaterial = new THREE.PointsMaterial({
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        color: 0xffffff,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              size: 0.7,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    transparent: true,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          opacity: 0.6,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  const particleSystem = new THREE.Points(particles, particleMaterial);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      scene.add(particleSystem);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          // ==========================
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              // ANIMAÇÃO CINEMATOGRÁFICA
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  // ==========================

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      const start = Date.now();

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          const introTime = 4500;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              const animate = () => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    requestAnimationFrame(animate);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          const elapsed = Date.now() - start;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if (elapsed < introTime) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        const progress = elapsed / introTime;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                const ease = 1 - Math.pow(1 - progress, 4);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        camera.position.z = 220 - ease * 185;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                camera.position.y = 15 - ease * 12;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        group.position.y = -10 + ease * 10;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                neon.intensity = 1 + Math.sin(elapsed * 0.005) * 2;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      } else {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              camera.position.x = Math.sin(elapsed * 0.002) * 0.15;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      camera.position.y = 3 + Math.cos(elapsed * 0.002) * 0.15;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  group.rotation.y = Math.sin(elapsed * 0.001) * 0.04;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        particleSystem.rotation.y += 0.0006;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              renderer.render(scene, camera);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    // TRANSIÇÃO AUTOMÁTICA PARA O JOGO
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          if (elapsed > 6200) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  window.location.href = "/game";
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            };

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                animate();

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    const resize = () => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          camera.aspect = window.innerWidth / window.innerHeight;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                camera.updateProjectionMatrix();

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      renderer.setSize(window.innerWidth, window.innerHeight);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          };

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              window.addEventListener("resize", resize);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  return () => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        window.removeEventListener("resize", resize);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              renderer.dispose();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }, []);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      return (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ref={containerRef}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      style={{
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              width: "100vw",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      height: "100vh",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              background: "#000",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      overflow: "hidden",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }
