import { useEffect, useRef } from "react";
import * as THREE from "three";

export default function CinematicIntro() {

  const containerRef = useRef<HTMLDivElement>(null);

    useEffect(() => {

        if (!containerRef.current) return;

            // SCENE
                const scene = new THREE.Scene();
                    scene.background = new THREE.Color(0x000000);
                        scene.fog = new THREE.Fog(0x000000, 40, 300);

                            // CAMERA
                                const camera = new THREE.PerspectiveCamera(
                                      70,
                                            window.innerWidth / window.innerHeight,
                                                  0.1,
                                                        1000
                                                            );

                                                                camera.position.set(0, 15, 220);

                                                                    // RENDERER
                                                                        const renderer = new THREE.WebGLRenderer({
                                                                              antialias: true,
                                                                                    powerPreference: "high-performance"
                                                                                        });

                                                                                            renderer.setSize(window.innerWidth, window.innerHeight);
                                                                                                renderer.setPixelRatio(window.devicePixelRatio);

                                                                                                    containerRef.current.appendChild(renderer.domElement);

                                                                                                        // LUZ AMBIENTE
                                                                                                            const ambientLight = new THREE.AmbientLight(0xffffff, 0.3);
                                                                                                                scene.add(ambientLight);

                                                                                                                    // HOLOFOTE
                                                                                                                        const spotLight = new THREE.SpotLight(0xffd700, 6, 300, Math.PI / 4, 0.5, 1);
                                                                                                                            spotLight.position.set(0, 80, 40);
                                                                                                                                scene.add(spotLight);

                                                                                                                                    // NEON
                                                                                                                                        const neonLight = new THREE.PointLight(0x00eaff, 2, 120);
                                                                                                                                            neonLight.position.set(0, -8, 20);
                                                                                                                                                scene.add(neonLight);

                                                                                                                                                    // GRUPO DO LETREIRO
                                                                                                                                                        const signGroup = new THREE.Group();
                                                                                                                                                            scene.add(signGroup);

                                                                                                                                                                // ==========================
                                                                                                                                                                    // CANVAS DO LETREIRO
                                                                                                                                                                        // ==========================

                                                                                                                                                                            const canvas = document.createElement("canvas");

                                                                                                                                                                                canvas.width = 2048;
                                                                                                                                                                                    canvas.height = 512;

                                                                                                                                                                                        const ctx = canvas.getContext("2d");

                                                                                                                                                                                            if (ctx) {

                                                                                                                                                                                                  // FUNDO
                                                                                                                                                                                                        ctx.fillStyle = "#050505";
                                                                                                                                                                                                              ctx.fillRect(0, 0, canvas.width, canvas.height);

                                                                                                                                                                                                                    ctx.textAlign = "center";
                                                                                                                                                                                                                          ctx.textBaseline = "middle";

                                                                                                                                                                                                                                // FONTE SEGURA
                                                                                                                                                                                                                                      ctx.font = "bold 160px Arial";

                                                                                                                                                                                                                                            // GRADIENTE OURO
                                                                                                                                                                                                                                                  const gradient = ctx.createLinearGradient(0, 0, 0, canvas.height);

                                                                                                                                                                                                                                                        gradient.addColorStop(0, "#fff2a8");
                                                                                                                                                                                                                                                              gradient.addColorStop(0.5, "#ffd700");
                                                                                                                                                                                                                                                                    gradient.addColorStop(1, "#8a6d3b");

                                                                                                                                                                                                                                                                          ctx.fillStyle = gradient;

                                                                                                                                                                                                                                                                                // SOMBRA NEON
                                                                                                                                                                                                                                                                                      ctx.shadowColor = "#00eaff";
                                                                                                                                                                                                                                                                                            ctx.shadowBlur = 25;

                                                                                                                                                                                                                                                                                                  // BORDA DO TEXTO
                                                                                                                                                                                                                                                                                                        ctx.lineWidth = 8;
                                                                                                                                                                                                                                                                                                              ctx.strokeStyle = "#000";

                                                                                                                                                                                                                                                                                                                    const text = "COMPLEXO DO COMANDO NORTE";

                                                                                                                                                                                                                                                                                                                          ctx.strokeText(text, canvas.width / 2, canvas.height / 2);
                                                                                                                                                                                                                                                                                                                                ctx.fillText(text, canvas.width / 2, canvas.height / 2);
                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                        const texture = new THREE.CanvasTexture(canvas);
                                                                                                                                                                                                                                                                                                                                            texture.needsUpdate = true;

                                                                                                                                                                                                                                                                                                                                                // MATERIAL
                                                                                                                                                                                                                                                                                                                                                    const signMaterial = new THREE.MeshStandardMaterial({
                                                                                                                                                                                                                                                                                                                                                          map: texture,
                                                                                                                                                                                                                                                                                                                                                                metalness: 0.9,
                                                                                                                                                                                                                                                                                                                                                                      roughness: 0.2,
                                                                                                                                                                                                                                                                                                                                                                            emissive: new THREE.Color(0x111111)
                                                                                                                                                                                                                                                                                                                                                                                });

                                                                                                                                                                                                                                                                                                                                                                                    const signMesh = new THREE.Mesh(
                                                                                                                                                                                                                                                                                                                                                                                          new THREE.PlaneGeometry(60, 15),
                                                                                                                                                                                                                                                                                                                                                                                                signMaterial
                                                                                                                                                                                                                                                                                                                                                                                                    );

                                                                                                                                                                                                                                                                                                                                                                                                        signGroup.add(signMesh);

                                                                                                                                                                                                                                                                                                                                                                                                            // MOLDURA
                                                                                                                                                                                                                                                                                                                                                                                                                const frame = new THREE.Mesh(
                                                                                                                                                                                                                                                                                                                                                                                                                      new THREE.BoxGeometry(64, 19, 1),
                                                                                                                                                                                                                                                                                                                                                                                                                            new THREE.MeshStandardMaterial({
                                                                                                                                                                                                                                                                                                                                                                                                                                    color: 0xffd700,
                                                                                                                                                                                                                                                                                                                                                                                                                                            metalness: 1,
                                                                                                                                                                                                                                                                                                                                                                                                                                                    roughness: 0.2
                                                                                                                                                                                                                                                                                                                                                                                                                                                          })
                                                                                                                                                                                                                                                                                                                                                                                                                                                              );

                                                                                                                                                                                                                                                                                                                                                                                                                                                                  frame.position.z = -0.5;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                      signGroup.add(frame);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                          // ==========================
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              // PARTÍCULAS
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  // ==========================

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      const particleCount = 1200;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          const particles = new THREE.BufferGeometry();

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              const positions = new Float32Array(particleCount * 3);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  for (let i = 0; i < particleCount; i++) {

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        positions[i * 3] = (Math.random() - 0.5) * 200;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              positions[i * 3 + 1] = Math.random() * 80 - 20;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    positions[i * 3 + 2] = (Math.random() - 0.5) * 200;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            particles.setAttribute(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  "position",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        new THREE.BufferAttribute(positions, 3)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            );

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                const particleMaterial = new THREE.PointsMaterial({
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      color: 0xffffff,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            size: 0.7,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  transparent: true,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        opacity: 0.6
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                const particleSystem = new THREE.Points(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      particles,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            particleMaterial
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                );

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    scene.add(particleSystem);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        // ==========================
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            // ANIMAÇÃO
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                // ==========================

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    const startTime = Date.now();

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        const introDuration = 6000;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            const animate = () => {

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  requestAnimationFrame(animate);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        const elapsed = Date.now() - startTime;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              if (elapsed < introDuration) {

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      const progress = elapsed / introDuration;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              const ease = 1 - Math.pow(1 - progress, 4);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      camera.position.z = 220 - ease * 180;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              camera.position.y = 15 - ease * 12;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      signGroup.position.y = -10 + ease * 10;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              neonLight.intensity = 1.5 + Math.sin(elapsed * 0.005) * 2;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    } else {

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            camera.position.x = Math.sin(elapsed * 0.002) * 0.15;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    camera.position.y = 3 + Math.cos(elapsed * 0.002) * 0.15;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                signGroup.rotation.y = Math.sin(elapsed * 0.001) * 0.04;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      particleSystem.rotation.y += 0.0005;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            renderer.render(scene, camera);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  // TRANSIÇÃO PARA O JOGO

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if (elapsed > 9000) {

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                document.body.style.transition = "opacity 1.5s";
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        document.body.style.opacity = "0";

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                setTimeout(() => {

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          window.location.href = "/game";

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }, 1500);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            };

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                animate();

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    // RESIZE

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        const handleResize = () => {

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              camera.aspect = window.innerWidth / window.innerHeight;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    camera.updateProjectionMatrix();

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          renderer.setSize(window.innerWidth, window.innerHeight);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              };

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  window.addEventListener("resize", handleResize);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      return () => {

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            window.removeEventListener("resize", handleResize);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  renderer.dispose();

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      };

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }, []);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          return (

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ref={containerRef}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          style={{
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  width: "100vw",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          height: "100vh",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  background: "#000",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          overflow: "hidden"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    />

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }
