import { Image } from '@/components/ui/image';
import { motion } from 'framer-motion';
import { useEffect, useRef, useState } from 'react';

interface LiveNPCProps {
  src: string;
    alt: string;
      onClick?: () => void;
        className?: string;
          width?: number;
            height?: number;
            }

            export default function LiveNPC({
              src,
                alt,
                  onClick,
                    className = '',
                      width = 400,
                        height = 800,
                        }: LiveNPCProps) {
                          const [mousePosition, setMousePosition] = useState({ x: 0, y: 0 });
                            const [isHovered, setIsHovered] = useState(false);
                              const [isPressed, setIsPressed] = useState(false);
                                const [blink, setBlink] = useState(false);

                                  const containerRef = useRef<HTMLDivElement>(null);

                                    // ⚠️ CORREÇÃO AQUI (remove NodeJS.Timeout que quebra em alguns ambientes)
                                      const blinkTimeoutRef = useRef<any>(null);
                                        const nextBlinkRef = useRef<any>(null);

                                          useEffect(() => {
                                              const scheduleNextBlink = () => {
                                                    const randomDelay = Math.random() * 3000 + 3000;

                                                          nextBlinkRef.current = setTimeout(() => {
                                                                  setBlink(true);

                                                                          blinkTimeoutRef.current = setTimeout(() => {
                                                                                    setBlink(false);
                                                                                              scheduleNextBlink();
                                                                                                      }, 150);
                                                                                                            }, randomDelay);
                                                                                                                };

                                                                                                                    scheduleNextBlink();

                                                                                                                        return () => {
                                                                                                                              if (blinkTimeoutRef.current) clearTimeout(blinkTimeoutRef.current);
                                                                                                                                    if (nextBlinkRef.current) clearTimeout(nextBlinkRef.current);
                                                                                                                                        };
                                                                                                                                          }, []);

                                                                                                                                            useEffect(() => {
                                                                                                                                                const handleMouseMove = (e: MouseEvent) => {
                                                                                                                                                      if (!containerRef.current) return;

                                                                                                                                                            const rect = containerRef.current.getBoundingClientRect();

                                                                                                                                                                  const centerX = rect.left + rect.width / 2;
                                                                                                                                                                        const centerY = rect.top + rect.height / 2;

                                                                                                                                                                              const deltaX = e.clientX - centerX;
                                                                                                                                                                                    const deltaY = e.clientY - centerY;

                                                                                                                                                                                          const distance = Math.sqrt(deltaX * deltaX + deltaY * deltaY);
                                                                                                                                                                                                const maxDistance = Math.max(rect.width, rect.height);

                                                                                                                                                                                                      const maxOffset = 5;
                                                                                                                                                                                                            const offset = Math.min((distance / maxDistance) * maxOffset, maxOffset);

                                                                                                                                                                                                                  const dirX = deltaX / distance || 0;
                                                                                                                                                                                                                        const dirY = deltaY / distance || 0;

                                                                                                                                                                                                                              setMousePosition({
                                                                                                                                                                                                                                      x: dirX * offset * 0.7,
                                                                                                                                                                                                                                              y: dirY * offset * 0.7,
                                                                                                                                                                                                                                                    });
                                                                                                                                                                                                                                                        };

                                                                                                                                                                                                                                                            window.addEventListener('mousemove', handleMouseMove);
                                                                                                                                                                                                                                                                return () => window.removeEventListener('mousemove', handleMouseMove);
                                                                                                                                                                                                                                                                  }, []);

                                                                                                                                                                                                                                                                    useEffect(() => {
                                                                                                                                                                                                                                                                        const handleMouseLeave = () => {
                                                                                                                                                                                                                                                                              setMousePosition({ x: 0, y: 0 });
                                                                                                                                                                                                                                                                                  };

                                                                                                                                                                                                                                                                                      window.addEventListener('mouseleave', handleMouseLeave);
                                                                                                                                                                                                                                                                                          return () => window.removeEventListener('mouseleave', handleMouseLeave);
                                                                                                                                                                                                                                                                                            }, []);

                                                                                                                                                                                                                                                                                              // 🔥 NÃO mexi na sua estrutura — só mantive igual
                                                                                                                                                                                                                                                                                                const breathingVariants = {
                                                                                                                                                                                                                                                                                                    animate: {
                                                                                                                                                                                                                                                                                                          scale: [1, 1.02, 1],
                                                                                                                                                                                                                                                                                                                transition: {
                                                                                                                                                                                                                                                                                                                        duration: 3.5,
                                                                                                                                                                                                                                                                                                                                ease: 'easeInOut',
                                                                                                                                                                                                                                                                                                                                        repeat: Infinity,
                                                                                                                                                                                                                                                                                                                                              },
                                                                                                                                                                                                                                                                                                                                                  },
                                                                                                                                                                                                                                                                                                                                                    };

                                                                                                                                                                                                                                                                                                                                                      const bodyMovementVariants = {
                                                                                                                                                                                                                                                                                                                                                          animate: {
                                                                                                                                                                                                                                                                                                                                                                y: [0, -2, 0],
                                                                                                                                                                                                                                                                                                                                                                      transition: {
                                                                                                                                                                                                                                                                                                                                                                              duration: 5,
                                                                                                                                                                                                                                                                                                                                                                                      ease: 'easeInOut',
                                                                                                                                                                                                                                                                                                                                                                                              repeat: Infinity,
                                                                                                                                                                                                                                                                                                                                                                                                    },
                                                                                                                                                                                                                                                                                                                                                                                                        },
                                                                                                                                                                                                                                                                                                                                                                                                          };

                                                                                                                                                                                                                                                                                                                                                                                                            const hoverVariants = {
                                                                                                                                                                                                                                                                                                                                                                                                                hover: {
                                                                                                                                                                                                                                                                                                                                                                                                                      scale: 1.05,
                                                                                                                                                                                                                                                                                                                                                                                                                            filter: 'brightness(1.1)',
                                                                                                                                                                                                                                                                                                                                                                                                                                  transition: {
                                                                                                                                                                                                                                                                                                                                                                                                                                          duration: 0.3,
                                                                                                                                                                                                                                                                                                                                                                                                                                                  ease: 'easeOut',
                                                                                                                                                                                                                                                                                                                                                                                                                                                        },
                                                                                                                                                                                                                                                                                                                                                                                                                                                            },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                normal: {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      scale: 1,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            filter: 'brightness(1)',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  transition: {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          duration: 0.3,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ease: 'easeOut',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              };

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                const pressVariants = {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    press: {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          scale: 0.97,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                transition: {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        duration: 0.1,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      release: {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            scale: isHovered ? 1.05 : 1,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  transition: {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          duration: 0.2,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ease: 'easeOut',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              };

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                // 🔥 CORREÇÃO AQUI (não apaga a NPC)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  const blinkVariants = {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      normal: {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            opacity: 1,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  transition: { duration: 0.05 },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          blink: {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                opacity: 1,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      transition: { duration: 0.05 },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            };

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              return (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ref={containerRef}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              className="relative"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    onMouseEnter={() => setIsHovered(true)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          onMouseLeave={() => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  setIsHovered(false);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          setIsPressed(false);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      onMouseDown={() => setIsPressed(true)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            onMouseUp={() => setIsPressed(false)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <motion.div variants={breathingVariants} animate="animate" className="relative">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <motion.div variants={bodyMovementVariants} animate="animate" className="relative">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <motion.div variants={hoverVariants} animate={isHovered ? 'hover' : 'normal'} className="relative">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <motion.div
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  variants={pressVariants}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                animate={isPressed ? 'press' : 'release'}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              className="relative"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            style={{
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            x: mousePosition.x,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            y: mousePosition.y,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <motion.div
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    variants={blinkVariants}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    animate={blink ? 'blink' : 'normal'}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    className="relative"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <Image
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    src={src}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      alt={alt}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        onClick={onClick}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          className={`relative z-10 cursor-pointer ${className}`}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            width={width}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              height={height}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              />

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              {blink && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <motion.div
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    initial={{ opacity: 0 }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        animate={{ opacity: 0.2 }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            transition={{ duration: 0.05 }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                className="absolute inset-0 pointer-events-none"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    style={{
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          top: '20%',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                height: '10%',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      background: 'rgba(0,0,0,0.15)',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </motion.div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </motion.div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </motion.div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </motion.div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </motion.div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
